//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idle.Resources.L10N {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Idle.Resources.L10N.LocalizationResource", typeof(LocalizationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It lets you see sharp. Ba dum tss..
        /// </summary>
        public static string Language_CSharp_Description {
            get {
                return ResourceManager.GetString("Language.CSharp.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C#.
        /// </summary>
        public static string Language_CSharp_Name {
            get {
                return ResourceManager.GetString("Language.CSharp.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A language like C# but not C#.
        /// </summary>
        public static string Language_Java_Description {
            get {
                return ResourceManager.GetString("Language.Java.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java.
        /// </summary>
        public static string Language_Java_Name {
            get {
                return ResourceManager.GetString("Language.Java.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A language for building android apps..
        /// </summary>
        public static string Language_Kotlin_Description {
            get {
                return ResourceManager.GetString("Language.Kotlin.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kotlin.
        /// </summary>
        public static string Language_Kotlin_Name {
            get {
                return ResourceManager.GetString("Language.Kotlin.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone uses this for stuff, big cringe..
        /// </summary>
        public static string Language_Python_Description {
            get {
                return ResourceManager.GetString("Language.Python.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python.
        /// </summary>
        public static string Language_Python_Name {
            get {
                return ResourceManager.GetString("Language.Python.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade.
        /// </summary>
        public static string LanguageCell_Button_Upgrade {
            get {
                return ResourceManager.GetString("LanguageCell.Button.Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learned.
        /// </summary>
        public static string LanguageItemCell_Button_Learned {
            get {
                return ResourceManager.GetString("LanguageItemCell.Button.Learned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Market.
        /// </summary>
        public static string LanguageMarket_Label_Language_Market {
            get {
                return ResourceManager.GetString("LanguageMarket.Label.Language-Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start speaking now!.
        /// </summary>
        public static string LanguageMarket_Label_Start_speaking_now {
            get {
                return ResourceManager.GetString("LanguageMarket.Label.Start-speaking-now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Market.
        /// </summary>
        public static string MainPage_Button_Language_Market {
            get {
                return ResourceManager.GetString("MainPage.Button.Language-Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string MainPage_Button_Languages {
            get {
                return ResourceManager.GetString("MainPage.Button.Languages", resourceCulture);
            }
        }
    }
}
